insert into role (role_id, title) values (1, 'Sales Associate');
insert into role (role_id, title) values (2, 'Recruiter');
insert into role (role_id, title) values (3, 'General Manager');
insert into role (role_id, title) values (4, 'VP Marketing');
insert into role (role_id, title) values (5, 'VP Product Management');
insert into role (role_id, title) values (6, 'Sales Representative');
insert into role (role_id, title) values (7, 'Speech Pathologist');
insert into role (role_id, title) values (8, 'Geologist I');
insert into role (role_id, title) values (9, 'Product Engineer');
insert into role (role_id, title) values (10, 'Recruiting Manager');
insert into role (role_id, title) values (11, 'Account Executive');
insert into role (role_id, title) values (12, 'Systems Administrator II');
insert into role (role_id, title) values (13, 'Desktop Support Technician');
insert into role (role_id, title) values (14, 'Human Resources Manager');
insert into role (role_id, title) values (15, 'Technical Writer');
insert into role (role_id, title) values (16, 'Web Developer II');
insert into role (role_id, title) values (17, 'Dental Hygienist');
insert into role (role_id, title) values (18, 'Recruiting Manager');
insert into role (role_id, title) values (19, 'Nurse');
insert into role (role_id, title) values (20, 'Research Nurse');
insert into role (role_id, title) values (21, 'Statistician III');
insert into role (role_id, title) values (22, 'Account Coordinator');
insert into role (role_id, title) values (23, 'Food Chemist');
insert into role (role_id, title) values (24, 'VP Accounting');
insert into role (role_id, title) values (25, 'Sales Associate');
insert into role (role_id, title) values (26, 'Director of Sales');
insert into role (role_id, title) values (27, 'Help Desk Technician');
insert into role (role_id, title) values (28, 'Office Assistant IV');
insert into role (role_id, title) values (29, 'Assistant Manager');
insert into role (role_id, title) values (30, 'Project Manager');
insert into role (role_id, title) values (31, 'Dental Hygienist');
insert into role (role_id, title) values (32, 'Help Desk Operator');
insert into role (role_id, title) values (33, 'Librarian');
insert into role (role_id, title) values (34, 'Marketing Manager');
insert into role (role_id, title) values (35, 'Nuclear Power Engineer');
insert into role (role_id, title) values (36, 'Marketing Manager');
insert into role (role_id, title) values (37, 'Health Coach II');
insert into role (role_id, title) values (38, 'Chemical Engineer');
insert into role (role_id, title) values (39, 'Information Systems Manager');
insert into role (role_id, title) values (40, 'Geologist III');
insert into role (role_id, title) values (41, 'Administrative Officer');
insert into role (role_id, title) values (42, 'Project Manager');
insert into role (role_id, title) values (43, 'Mechanical Systems Engineer');
insert into role (role_id, title) values (44, 'Quality Control Specialist');
insert into role (role_id, title) values (45, 'Quality Control Specialist');
insert into role (role_id, title) values (46, 'VP Product Management');
insert into role (role_id, title) values (47, 'Senior Sales Associate');
insert into role (role_id, title) values (48, 'Assistant Manager');
insert into role (role_id, title) values (49, 'Software Test Engineer IV');
insert into role (role_id, title) values (50, 'Senior Financial Analyst');
insert into role (role_id, title) values (51, 'Office Assistant IV');
insert into role (role_id, title) values (52, 'Accountant II');
insert into role (role_id, title) values (53, 'Speech Pathologist');
insert into role (role_id, title) values (54, 'Editor');
insert into role (role_id, title) values (55, 'Editor');
insert into role (role_id, title) values (56, 'Assistant Manager');
insert into role (role_id, title) values (57, 'Executive Secretary');
insert into role (role_id, title) values (58, 'Senior Sales Associate');
insert into role (role_id, title) values (59, 'Information Systems Manager');
insert into role (role_id, title) values (60, 'Senior Financial Analyst');
insert into role (role_id, title) values (61, 'Software Test Engineer IV');
insert into role (role_id, title) values (62, 'Data Coordiator');
insert into role (role_id, title) values (63, 'Editor');
insert into role (role_id, title) values (64, 'Product Engineer');
insert into role (role_id, title) values (65, 'Teacher');
insert into role (role_id, title) values (66, 'Registered Nurse');
insert into role (role_id, title) values (67, 'Environmental Tech');
insert into role (role_id, title) values (68, 'Teacher');
insert into role (role_id, title) values (69, 'Analyst Programmer');
insert into role (role_id, title) values (70, 'Database Administrator III');
insert into role (role_id, title) values (71, 'Marketing Manager');
insert into role (role_id, title) values (72, 'Environmental Specialist');
insert into role (role_id, title) values (73, 'Business Systems Development Analyst');
insert into role (role_id, title) values (74, 'Compensation Analyst');
insert into role (role_id, title) values (75, 'Software Engineer I');
insert into role (role_id, title) values (76, 'Computer Systems Analyst II');
insert into role (role_id, title) values (77, 'Senior Financial Analyst');
insert into role (role_id, title) values (78, 'Environmental Tech');
insert into role (role_id, title) values (79, 'Senior Developer');
insert into role (role_id, title) values (80, 'Internal Auditor');
insert into role (role_id, title) values (81, 'VP Product Management');
insert into role (role_id, title) values (82, 'VP Quality Control');
insert into role (role_id, title) values (83, 'Assistant Manager');
insert into role (role_id, title) values (84, 'Product Engineer');
insert into role (role_id, title) values (85, 'VP Marketing');
insert into role (role_id, title) values (86, 'Research Assistant II');
insert into role (role_id, title) values (87, 'Technical Writer');
insert into role (role_id, title) values (88, 'Marketing Manager');
insert into role (role_id, title) values (89, 'Occupational Therapist');
insert into role (role_id, title) values (90, 'Speech Pathologist');
insert into role (role_id, title) values (91, 'Environmental Specialist');
insert into role (role_id, title) values (92, 'Health Coach IV');
insert into role (role_id, title) values (93, 'Senior Developer');
insert into role (role_id, title) values (94, 'Analyst Programmer');
insert into role (role_id, title) values (95, 'Database Administrator I');
insert into role (role_id, title) values (96, 'Accounting Assistant III');
insert into role (role_id, title) values (97, 'Project Manager');
insert into role (role_id, title) values (98, 'Database Administrator I');
insert into role (role_id, title) values (99, 'Research Associate');
insert into role (role_id, title) values (100, 'Nurse Practicioner');